### ISSUE TITLE
FB endpoints

### ISSUE THREAD

**Issue by pmaliszewski** [MichalKarol/pyfocalboard#1]
https://github.com/MichalKarol/pyfocalboard/blob/b241eb588b6b259949b059d4eb70219b69b31e1a/pyfocalboard/api.py#L38

This should be abstracted out. Mattermost's FB requires wacky workarounds, but it does exist (or at least, used to exist) as a project fully outside MM. It has different endpoints in said case.

**Comment by MichalKarol** [comment]
Added `is_standalone` and `non_standard_api_url` params to handle more complex cases when FB is not used as a plugin.
