### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by pmaliszewski** [MichalKarol/pyfocalboard#4]
https://github.com/MichalKarol/pyfocalboard/blob/b241eb588b6b259949b059d4eb70219b69b31e1a/pyfocalboard/api.py#L47

What if it breaks in any other way? There's a lot of trust being placed into this method instead of just checking for != 2xx codes.

**Comment by MichalKarol** [comment]
Added _check_response to validate the FB API response status code and content.
